export default {
    print: {
        loadFailed: 'Something went wrong loading the report.',
        salesReport: 'Sales Report',
        dateRange: 'From {from} to {to}',
        printedOn: 'Printed on: {date}',
        totalCollected: 'Total collected',
        outstanding: 'Outstanding',
        ordersByCustomer: 'Orders by Customer',
        ordersCount: 'Orders',
        collected: 'Collected',
        dailyBreakdown: 'Daily Breakdown',
        profitByOrder: 'Profit by Order',
        profit: 'Profit',
        margin: 'Margin',
        paymentsHistory: 'Payments History',
        generatedBy: '{business} — Generated by MultiDukkan',
    },
}
